name: Windows Auto-Setup
on: 
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - name: Download scripts
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/Ali-157/testing/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          Invoke-WebRequest -Uri "https://gitlab.com/Ali-157/testing/-/raw/main/show.bat" -OutFile "show.bat"
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/loop-win10/-/raw/main/loop.bat" -OutFile "loop.bat"

      - name: Run installation
        run: |
          cmd /c Downloads.bat
          taskkill /IM WindowsTerminal.exe /F
          cmd /c show.bat
          cmd /c loop.bat

      - name: Cleanup
        run: |
          del Downloads.bat
          del show.bat
          del loop.bat
