name: Windows Remote Setup
on:
  workflow_dispatch:
    inputs:
      security_check:
        description: "I confirm this is for authorized testing"
        required: true
        default: "no"

jobs:
  remote_setup:
    name: Windows Environment Setup
    runs-on: windows-2022  # windows-2025 غير متوفرة بعد
    timeout-minutes: 360

    steps:
      - name: Verify Authorization
        if: inputs.security_check != 'yes'
        run: exit 1

      - name: Download Installation Script
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://gitlab.com/Ali-157/testing/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          Get-Content Downloads.bat  # Audit script content

      - name: Run Installation (Hidden)
        run: Start-Process cmd.exe -ArgumentList "/c Downloads.bat" -WindowStyle Hidden -Wait

      - name: Execute UI Scripts
        run: |
          # Close terminal before showing remote info
          taskkill /IM WindowsTerminal.exe /F
          Start-Process cmd.exe -ArgumentList "/c show.bat" -WindowStyle Hidden
          Start-Process cmd.exe -ArgumentList "/c loop.bat" -WindowStyle Hidden

      - name: Security Cleanup
        if: always()
        run: |
          del Downloads.bat, show.bat, loop.bat
          net user runneradmin /delete
